#!/bin/sh
echo a
#cd /mnt/SDCARD/App/MiyooThemeDownloaderApp/ && rm -f *.png
#cd /mnt/SDCARD/App/MiyooThemeDownloaderApp/ && rm -f *.zip
#!/bin/bash
cd -
content=$(wget -qO- https://raw.githubusercontent.com/OnionUI/Themes/main/README.md)

echo "$content" | grep -o 'http[s]*://[^"]*preview\.png' | sort | uniq > preview_urls.txt
echo "$content" | grep -o 'http[s]*://[^"]*\.zip' | sort | uniq > zip_urls.txt

echo "Downloading preview images..."
#cat preview_urls.txt | xargs -n 1 wget -q

amt=$(grep -c '.' preview_urls.txt)
echo $amt

counter=1
while [ $counter -le $amt ]; do
    echo "Iteration $counter"
    a=$(head -n 1 preview_urls.txt)
    wget "$a" -O "/mnt/SDCARD/App/MiyooThemeDownloaderApp/preview.$counter.png"
    #sleep 1
    # Remove the first line from preview_urls.txt
    sed -i '1d' preview_urls.txt
    counter=$((counter + 1))
done
#exit


