#!/bin/sh
#cd /mnt/SDCARD/App/themestore/ && rm -f *.png
#cd /mnt/SDCARD/App/themestore/ && rm -f *.zip
cd -
content=$(wget -qO- https://raw.githubusercontent.com/OnionUI/Themes/main/README.md)

echo "$content" | grep -o 'http[s]*://[^"]*preview\.png' | sort | uniq > preview_urls.txt
echo "$content" | grep -o 'http[s]*://[^"]*\.zip' | sort | uniq > zip_urls.txt
echo "Downloading preview images..."
amt=$(grep -c '.' preview_urls.txt)
echo $amt
counter=1
while [ $counter -le $amt ]; do
    echo "Iteration $counter"
    a=$(head -n 1 preview_urls.txt)
    wget "$a" -O "/mnt/SDCARD/App/themestore/preview.$counter.png"
    #sleep 1
    sed -i '1d' preview_urls.txt
    counter=$((counter + 1))
done



